### ISSUE TITLE
안드로이드 가이드라인 개편 관련

### ISSUE THREAD

**Issue by devussy** [BBBInc/android-guidelines#2]
앞으로 더 많은 개발자분들이 입사 예정입니다.
그래서 그 전에 현재 가이드의 부족한 부분(엄청 많음...)과
업무 수행하면서 변경됐던 사항 중 미반영 된 내용(역시 엄청 많음...)을 작성하여 한 번 더 개편하려 합니다.

작성하면서 우리가 왜 이렇게 가이드라인을 작성했는지에 대한 기록을 남기기 위해
*모든 변경사항*과 *모든 질문사항*은 `Issues`와 `Pull request`로 진행하도록 하겠습니다.

가이드라인 이외의 문서는 논의를 거쳐 별도 Repository에 보관하도록 하겠습니다.

[ribot/android-guideline](https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md)을 많이 참고할 것 같습니다.

많은 도움 바랍니다 영평님 ㅎㅎ

**Comment by bbb-levin** [comment]
하하하... ^^ 차근차근히 해보죠
